version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: oddsuser
      POSTGRES_PASSWORD: oddspassword
      POSTGRES_DB: oddsdb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./odds-dashboard
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: oddsuser
      DB_PASSWORD: 
      DB_NAME: oddsdb
    depends_on:
      - postgres
  
  writer-service:
    build: ./writer-service
    ports:
      - "8081:8080"
    environment:
      PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: oddsuser
      DB_PASSWORD: oddspassword
      DB_NAME: oddsdb
    depends_on:
      - postgres

volumes:
  postgres-data: